export const VENUE_TIME_ZONE=process.env.VENUE_TIME_ZONE||"Europe/Minsk";
export const SITE_WAKE_MINUTE=6*60;
export const ORDER_OPEN_MINUTE=10*60;
export const ORDER_CLOSE_MINUTE=23*60;

export function venueMinute(date=new Date(),timeZone=VENUE_TIME_ZONE){
  const parts=new Intl.DateTimeFormat("en-GB",{timeZone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date);
  const values=Object.fromEntries(parts.map(part=>[part.type,part.value]));
  return Number(values.hour)*60+Number(values.minute);
}

export function isSiteSleepWindow(date=new Date(),timeZone=VENUE_TIME_ZONE){return venueMinute(date,timeZone)<SITE_WAKE_MINUTE}
export function isOrderingOpen(date=new Date(),timeZone=VENUE_TIME_ZONE){const minute=venueMinute(date,timeZone);return minute>=ORDER_OPEN_MINUTE&&minute<ORDER_CLOSE_MINUTE}
export function millisecondsUntilSiteWake(date=new Date(),timeZone=VENUE_TIME_ZONE){return Math.max(60_000,(SITE_WAKE_MINUTE-venueMinute(date,timeZone))*60_000)}

export function closedPageHtml(){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08090b"><title>Проект временно закрыт</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:#08090b;color:#f7f7f4;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif}.card{width:min(520px,100%);padding:34px;border:1px solid rgba(255,255,255,.1);border-radius:28px;background:#111318;text-align:center;box-shadow:0 30px 90px rgba(0,0,0,.35)}.brand{font-size:12px;font-weight:760;letter-spacing:.16em;text-transform:uppercase;color:#92979f}.sleeping-mascot{position:relative;width:132px;height:101px;margin:22px auto 20px;display:grid;place-items:center;animation:float 5s ease-in-out infinite}.mascot-art{display:block;width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 9px 11px rgba(0,0,0,.28));transform-origin:50% 78%;animation:breathe 4.2s ease-in-out infinite}.sleep-mark{position:absolute;color:#d9dde4;font-weight:760;line-height:1;opacity:0;animation:drift 3.6s ease-out infinite}.sleep-mark:nth-child(2){top:23px;right:0;font-size:11px}.sleep-mark:nth-child(3){top:7px;right:-12px;font-size:14px;animation-delay:1.2s}.sleep-mark:nth-child(4){top:-12px;right:-22px;font-size:18px;animation-delay:2.4s}h1{margin:0;font-size:30px;letter-spacing:-.035em}p{margin:14px auto 0;max-width:380px;color:#a4a8af;font-size:16px;line-height:1.55}@keyframes float{0%,100%{transform:translateY(3px)}50%{transform:translateY(-5px)}}@keyframes breathe{0%,100%{transform:scale(1)}50%{transform:scale(1.012,.992)}}@keyframes drift{0%{opacity:0;transform:translate(0,5px) scale(.88)}24%,68%{opacity:.9}100%{opacity:0;transform:translate(7px,-9px) scale(1.05)}}@media(max-width:420px){.card{padding:30px 22px}.sleeping-mascot{width:124px;height:95px;margin-top:20px}.sleep-mark:nth-child(2){top:22px;right:0}.sleep-mark:nth-child(3){top:7px;right:-10px}.sleep-mark:nth-child(4){top:-10px;right:-16px}h1{font-size:27px}}@media(prefers-reduced-motion:reduce){.sleeping-mascot,.mascot-art,.sleep-mark{animation:none}.sleep-mark{opacity:.78}}</style></head><body><main class="card"><div class="brand">Проект</div><div class="sleeping-mascot" aria-hidden="true"><img class="mascot-art" src="/assets/sleeping-mascot-v1.webp" alt="" width="744" height="552"><span class="sleep-mark">z</span><span class="sleep-mark">z</span><span class="sleep-mark">Z</span></div><h1>Ушли отдыхать, скоро вернемся</h1><p>Работаем с 10:00 до 23:00</p></main></body></html>`}
