const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.join(__dirname,'..');const validation=fs.readFileSync(path.join(root,'public/order-validation.js'),'utf8');
function fixture(){const fields=new Map();const document={addEventListener(){},querySelectorAll(){return []},getElementById(id){if(!fields.has(id))fields.set(id,{hidden:id==='trackingCard',querySelector(){return null},addEventListener(){},classList:{add(){},remove(){},toggle(){}},style:{},setAttribute(k,v){this[k]=v},scrollIntoView(){},value:'',innerHTML:''});return fields.get(id)}};const c={document,console,addEventListener(){},location:{origin:'https://example.test'},localStorage:{getItem(){return ''},setItem(){},removeItem(){}},setTimeout(){},clearTimeout(){},setInterval(){return 1},clearInterval(){},fetch:async()=>({ok:true,json:async()=>({categories:[],products:[],order:{status:'accepted',order_items:[]}})})};c.window=c;vm.createContext(c);vm.runInContext(validation,c);vm.runInContext([...fs.readFileSync(path.join(root,'public/index.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n'),c);return c;}
test('phone validation requires Belarus prefix and nine digits',()=>{const v=fixture().OrderValidation;for(const s of ['+375291234567','+375 (29) 123-45-67'])assert.equal(v.normalizePhone(s),'+375291234567');for(const s of ['291234567','+7291234567','+375','+3752912345678','+375abc291234567'])assert.equal(v.normalizePhone(s),'');});
test('comments filter whole words without blocking ordinary food requests',()=>{const v=fixture().OrderValidation;for(const s of ['Без лука, пожалуйста','Страхуем доставку','Хлеб и соль','ребенок ждет'])assert.equal(v.hasProfanity(s),false,s);for(const s of ['БЛЯТЬ!','сука','пиздец','fuck','хуй'])assert.equal(v.hasProfanity(s),true,s);assert.ok(v.validate({phone:'+375291234567',items:[{comment:'блять'}]}));});
test('website does not expose customer order tracking',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.doesNotMatch(html,/id="trackingLink"|id="trackingCard"|prilavok_tracking_token|startTrackingPolling|renderTracking|toggleTracking/);});
test('paste full number in fixed prefix field',()=>{const c=fixture(),input={value:'+375 (29) 123-45-67'};c.formatPhoneInput(input);assert.equal(input.value,'291234567');});
test('checkout rejects bad phone and profanity before database access',async()=>{const {mountOwnerRoutes,ownerBotAuthorized}=await import('../owner-auth.js');const {createPhoneVerificationService}=await import('../phone-verification.js');const {createCheckoutService}=await import('../checkout-service.js');const routes={};const app={use(){},get(){},put(){},patch(){},delete(){},post(path,handler){routes[path]=handler},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};const c={console,express,mountOwnerRoutes,ownerBotAuthorized,createPhoneVerificationService,createCheckoutService,createAvailabilityService:()=>({}),cors:()=>{},process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>({from(){throw Error('Database must not be accessed')}}),setInterval(){},randomUUID:()=>''};vm.createContext(c);vm.runInContext(validation,c);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),c);for(const body of [{phone:'+72912345678',comment:''},{phone:'+375291234567',comment:'блять'}]){const res={status(n){this.code=n;return this},json(value){this.body=value;return this}};await routes['/api/checkout']({protocol:'https',get:()=> 'example.test',body:{...body,customerName:'Тест',items:[{productId:'1',quantity:1}]}},res);assert.equal(res.code,400);assert.ok(res.body.error);}});

test('product detail updates quantity without reopening the screen',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/function refreshProductDetail\(id\)\{if\(activeProductId!==id\)return/);assert.doesNotMatch(html,/function refreshProductDetail\(id\)\{openProductDetail\(id\)\}/);assert.match(html,/refreshProductDetail\(id\);animateCartAdd\(d\)/);});
test('product detail uses transition based visibility instead of display toggling',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/\.product-detail\{[^}]*visibility:hidden;opacity:0/);assert.match(html,/\.product-detail\.is-open\{[^}]*visibility:visible;opacity:1/);assert.doesNotMatch(html,/productDetail'\)\.style\.display='block'/);});

test('Owner rollout also protects legacy phone confirmation from a forged callback',async()=>{
 const {mountOwnerRoutes,ownerBotAuthorized}=await import('../owner-auth.js');
 const routes={};let confirmations=0;
 const app={use(){},get(){},put(){},patch(){},delete(){},post(p,h){routes[p]=h},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};
 const context={console,express,setInterval(){},cors:()=>{},mountOwnerRoutes,ownerBotAuthorized,process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test',OWNER_AUTH_ENABLED:'true',OWNER_BOT_SHARED_SECRET:'s'.repeat(43)}},createClient:()=>({}),createPhoneVerificationService:()=>({confirm:async()=>{confirmations++;return {ok:true}}}),createAvailabilityService:()=>({}),createCheckoutService:()=>({finalizeByVerificationToken:async()=>({ok:true})})};
 vm.createContext(context);vm.runInContext(validation,context);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),context);
 for(const secret of [undefined,'wrong','s'.repeat(43)]){const res={status(n){this.code=n;return this},json(value){this.body=value;return this}};await routes['/api/phone-verification/:token/confirm']({header:()=>secret,body:{phone:'+375291234567',telegramUserId:123},params:{token:'token'}},res);assert.equal(res.code||200,secret==='s'.repeat(43)?200:403);}
 assert.equal(confirmations,1);
});

test('demand status is preloaded and refresh lifecycle stays production-safe',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/Обычная загруженность/);assert.match(html,/Ваш заказ постараются приготовить быстро/);assert.match(html,/Повышенная загруженность/);assert.match(html,/Заказ может готовиться дольше обычного/);assert.match(html,/Статус загруженности временно недоступен/);assert.match(html,/async function preloadDemandStatus\(\)/);assert.match(html,/void preloadDemandStatus\(\);loadMenu\(\)/);assert.doesNotMatch(html,/window\.__DEMAND_LAST=null/);assert.match(html,/const DEMAND_REFRESH_MS=25000/);assert.match(html,/demandRefreshTimer=setTimeout\(\(\)=>scheduleDemandStatus\(\{quiet:true\}\),DEMAND_REFRESH_MS\)/);assert.match(html,/demandController\?\.abort\(\).*demandSeq\+\+/s);assert.match(html,/if\(seq!==demandSeq\)return/);assert.match(html,/visibilitychange/);});

test('demand status failure is informational and does not gate checkout',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');const submit=html.slice(html.indexOf('async function submitOrder()'),html.indexOf('function statusInfo'));assert.doesNotMatch(submit,/DEMAND_LAST|demandController|scheduleDemandStatus|available/);assert.match(submit,/fetch\(API\+'\/api\/checkout'/);assert.match(submit,/location\.href=j\.telegramUrl/);assert.doesNotMatch(submit,/trackingToken|localStorage/);});

test('demand UI contains no retired ETA naming',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/id="demandCard"/);assert.match(html,/class="demand-card/);assert.doesNotMatch(html,/etaCard|eta-card|eta-title|eta-time|eta-note/);assert.match(html,/\/api\/demand\/status/);});

test('website enforces server availability on cards, cart refresh and checkout',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/function productLimit\(p\)/);assert.match(html,/Нет в наличии/);assert.match(html,/current>=limit/);assert.match(html,/refreshMenuAvailability\(\{announce:true\}\)/);assert.match(html,/Проверяем остатки/);assert.match(html,/available_quantity/);});
test('guest pages share full-width shell and one animated sold-out treatment',()=>{const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),shell=fs.readFileSync(path.join(root,'public/guest-shell.css'),'utf8');assert.match(order,/<link rel="stylesheet" href="\/guest-shell\.css">/);assert.match(menu,/<link rel="stylesheet" href="\/guest-shell\.css">/);assert.ok(order.indexOf('<header class="site-top"')<order.indexOf('<div class="wrap">'));assert.ok(menu.indexOf('<header class="top"')<menu.indexOf('<div class="shell">'));assert.match(shell,/\.site-top,\.top\{[^}]*width:100%/);assert.match(shell,/\.sold-out-layer::before\{[^}]*animation:soldOutSweep/);assert.match(shell,/@media\(prefers-reduced-motion:reduce\)/);assert.doesNotMatch(order,/Сегодня закончилось/);assert.doesNotMatch(menu,/Сегодня закончилось/);assert.doesNotMatch(order,/<div class="food-bg"/);assert.doesNotMatch(menu,/<div class="food-bg"/);assert.match(menu,/function productAvailable\(p\)/);});

test('guest branding and product controls use shared visual tokens',()=>{const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),shell=fs.readFileSync(path.join(root,'public/guest-shell.css'),'utf8');assert.match(order,/<title>Проект<\/title>/);assert.match(menu,/<title>Проект<\/title>/);assert.match(shell,/--guest-control-radius:999px/);assert.match(shell,/--guest-card-radius:24px/);assert.match(shell,/\.site-top \.brand,\.top \.brand/);assert.match(shell,/\.add,\.unavailable\{[^}]*min-height:42px/);assert.match(shell,/\.product-wrap \.unavailable\{margin-top:12px/);});

test('product roulette is shared, category-aware and excludes unavailable products',()=>{const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),roulette=fs.readFileSync(path.join(root,'public/guest-roulette.js'),'utf8'),shell=fs.readFileSync(path.join(root,'public/guest-shell.css'),'utf8');for(const html of [order,menu]){assert.match(html,/id="rouletteLaunch"/);assert.match(html,/<script src="\/guest-roulette\.js"><\/script>/);assert.match(html,/GuestRoulette\?\.mount/)}assert.match(roulette,/options\.isAvailable\(product\)/);assert.match(roulette,/String\(product\.category_id\)===String\(categoryId\)/);assert.match(roulette,/crypto\?\.getRandomValues/);assert.match(roulette,/Открыть товар/);assert.match(roulette,/finishTimer=setTimeout\(\(\)=>finish\(items\),2600\)/);assert.doesNotMatch(roulette,/Рулетка блюд|Рулетка крутится/);assert.match(shell,/\.roulette-select-wrap::after/);assert.match(shell,/\.cartbar::after\{[^}]*height:calc\(120px \+ env\(safe-area-inset-bottom\)\)/);assert.doesNotThrow(()=>new Function(roulette));});

test('online menu and online ordering use separate product visibility channels',()=>{
 const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),server=fs.readFileSync(path.join(root,'server.js'),'utf8');
 assert.match(order,/fetch\(API\+'\/api\/menu'/);assert.match(menu,/fetch\('\/api\/menu\?surface=menu'/);
 assert.match(server,/visible_in_menu: p\.visibleInOnlineMenu !== false/);assert.match(server,/menuSurface \? "visible_in_menu" : "available_online"/);
 assert.match(server,/missingOnlineMenuColumn/);assert.match(server,/withoutOnlineMenuColumn/);
});

test('menu endpoint selects the requested visibility column',async()=>{
 const routes={},filters=[];
 const app={use(){},get(path,handler){routes[path]=handler},put(){},patch(){},delete(){},post(){},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};
 const query=table=>{const q={select(){return q},eq(key,value){filters.push({table,key,value});return q},order(){return q},then(resolve){resolve({data:[],error:null})}};return q};
 const context={console,express,cors:()=>{},mountOwnerRoutes(){},ownerBotAuthorized(){return true},createPhoneVerificationService:()=>({}),createCheckoutService:()=>({}),createAvailabilityService:()=>({attachToProducts:async products=>products}),calculateLoyaltyTransition(){},loyaltyIdempotencyKey(){},validateLoyaltyAllocation(){},randomUUID:()=>'',process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>({from:query}),setInterval(){}};
 vm.createContext(context);vm.runInContext(validation,context);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),context);
 const response={json(value){this.body=value;return this},status(value){this.code=value;return this}};
 await routes['/api/menu']({query:{}},response);await routes['/api/menu']({query:{surface:'menu'}},response);
 assert.deepEqual(filters.filter(row=>row.table==='products'&&row.key!=='is_active').map(row=>row.key),['available_online','visible_in_menu']);
});
